Story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tugas.urls', namespace='story'))
    
]

tugas/urls.py
from django.urls import path, include
from . import views

app_name = 'story'

urlpatterns = [
    path('',views.home,name='Home'),
    path('more/',views.more,name='More'),
    path('bio/',views.bio,name='Bio'),
    path('schedule/',views.schedule,name='Schedule'),
    path('delete/<int:item>',views.delete, name = 'delete')
]

tugas/models.py
from django.db import models

class jadwal(models.Model):
    kegiatan = models.CharField(max_length=100)
    kategori = models.CharField(max_length=20)
    tempat = models.CharField(max_length=20)
    tanggal = models.DateField()

      

tugas/forms.py
from django import forms
from .models import jadwal
##Create your forms here
class JadwalForm(forms.ModelForm):
    """Form definition for MODELNAME."""

    class Meta:
        """Meta definition for MODELNAMEform."""

        model = jadwal
        fields = '__all__'

    # Kegiatan = forms.CharField(max_length=100)
    # Lokasi = forms.CharField(max_length=30)
    # kategori = forms.CharField(max_length=20)
    # Tanggal = forms.DateField()

tugas/views.py
from django.shortcuts import render,redirect
from .forms import JadwalForm
from .models import jadwal
from django.http import HttpResponse

# Create your views here.
def home(request):
    return render(request,'pages/index.html',{})

def more(request):
    return render(request,'pages/Story3more.html',{})

def bio(request):
    return render(request,'pages/Story3bio.html',{})

def schedule(request):
    posts = jadwal.objects.all(); 
    if request.method == 'POST':
        form = JadwalForm(request.POST)
        if form.is_valid():

            u = form.save()

            return redirect('/schedule')

    else:
        form = JadwalForm

    return render(request,'pages/Jadwal.html',{'form':form,'posts': posts})

def delete(request, item):
    jadwal.objects.filter(id=item).delete()
    return redirect('/schedule')

tugas/templates/pages/Jadwal.html
<!-- <form>
        <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
        </div>
        <div class="form-group form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Check me out</label>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form> -->
    {% load static %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        {% include 'pages/stylesh.html' %}
        <title>Farrel Alfarabi Saleh's Schedule</title>
    </head>
    <body>
        {% include 'pages/navbar.html' %}
        <h1 style="text-align: center">SUBMIT YOUR ACTIVITES</h1>
        <div>
            <form method="post">
                {% csrf_token %}
                <table>{{ form.as_table }}</table>
                <button type="submit">Submit</button>
            </form>
        </div>
        <table class="table table-dark">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Activity</th>
                    <th scope="col">Category</th>
                    <th scope="col">Location</th>
                    <th scope="col">Date</th>
                    <th scope="col">Delete</th>
                  </tr>
                </thead>
                <tbody>
                    {% for post in posts %}
                    <tr>
                        <th scope="row">{{forloop.counter}}</th>
                        <td>{{post.kegiatan}}</td>
                        <td>{{post.kategori}}</td>
                        <td>{{post.tempat}}</td>
                        <td>{{post.tanggal}}</td>
                        <td><a href="{% url 'story:delete' post.id %}"class="btn-outline btn-danger">Delete</a></td>

                    </tr>
                    {%endfor%}
                </tbody>
              </table> 
    </body>
    </html>  

tugas/templates/pages/Story3bio.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'pages/stylesh.html' %}
    <title>Farrel Alfarabi Saleh's Bio</title>
</head>
<body>
    {% include 'pages/navbar.html' %}
    <div>
        <div class="row center center2">
                <img src="{% static "assets\abi-ganteng.jpg" %}" class="col abi-ganteng">
                <div class="col rectangle rec2">
                        <div class="container box-container">
                            <article class="bio-text">
                                    Full Name: Farrel Alfarabi Saleh <br>Age: 19 <br>Nationality: Indonesia <br>Address: Jln Camar 24 Bintaro, Tangerang Selatan <br>College : Fasilkom UI <br>NPM : 1806186622 <br>Hobby : Film and video game
                            </article>
                        </div>
                </div>
        </div>
    </div>
</body>
</html>   

tugas/templates/pages/Story3more.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'pages/stylesh.html' %}
    <title>Farrel Alfarabi Saleh's More</title>
</head>
<body>
    {% include 'pages/navbar.html' %}
    <div class="main-more">
        <div class="center">
            <h2 class="short">“It’s not who I am underneath, but what I do that defines me.”</h2>
        </div>
    </div>
    <div class="row funfact">
        <img src="{% static "assets\abi-keren-blur.jpg" %}" class="col abi-keren">
        <h3 class="col facttitle">A few fun facts about myself: <br><br>My friends call me Abi.<br><br> I have a passion for programming and film.<br><br> My favorite number is 420.<br><br> I spend my lone time watching movies and playing video games.<br><br> I would like to say that i am an ambivert. </h3>
    </div>
</body>
</html>   

tugas/templates/pages/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'pages/stylesh.html' %}
    <title>Farrel Alfarabi Saleh's Profile</title>
</head>
<body>
    {% include 'pages/navbar.html' %}

    <div class="center">
        <h2 class="short">Hello, I’m Farrel. Welcome to my website.</h2>
        <h3 class="shortdesc"> I am a Computer Science student from Universitas Indonesia. The world is filled with problems that needs to be solved. It is our duty to solve these problems and i am always happy to help.</h3>
    </div>
    <div class= "center bottom">
        <div class="rectangle">
            <div class="container box-container">
                <div class = "row box-row">
                    <div class="col jobcol">
                        <img src="{% static "assets\design-pic.png" %}" class="pen">
                    </div>
                    <div class="col jobcol">
                        <img src="{% static "assets\pc.svg" %}" class="computer">
                    </div>
                </div>
                <div class="row box-row">
                    <div class="col jobcol">
                        <article class="job2">Designer</article>
                    </div>
                    <div class="col jobcol">
                        <article class="job2">Programmer</article>
                    </div>
                </div>
                <div class="row box-row">
                    <div class="col box-col">
                        <article class="skills">Things I enjoy designing:<br> UX, UI, Web, Mobile, Apps, Logos</article>
                    </div>
                    <div class="col box-col">
                        <article class="skills">Things I enjoy creating:<br> Games, Websites, Apps </article>
                    </div>
                </div>
                <div class="row box-row">
                    <div class="col box-col">
                        <article class="skills">Design Tools: Figma Marvel Pen & Paper</article>
                    </div>
                    <div class="col box-col">
                        <article class="skills">Programming Tools: Java Python HTML</article>
                    </div>
                </div>
            </div>
    </div>
    </div>
</body>
</html>       

tugas/templates/pages/navbar.html
{% load staticfiles %}
<nav class="main-nav">
    <div class="navigation left">
        <h1 class="job">WEB DESIGNER <br>& PROGRAMMER</h1>
        <img src="{% static "assets\Laptop-Free-Download-PNG.png" %}" class="laptop"> 
    </div>
    <div class="navigation right">
        <button onclick="window.location.href ='../schedule';" class="button astext">MY SCHEDULE</button>
        <button onclick="window.location.href ='../more';" class="button astext">MORE ABOUT ME</button>
        <button onclick="window.location.href ='../bio';" class="button astext">BIO</button>
        <button onclick="window.location.href ='../';" class="button astext">MAIN</button>   
    </div>
</nav>

tugas/templates/pages/stylesh.html
{% load staticfiles %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel='stylesheet' href="{% static 'bootstrap\css\bootstrap.css' %}">
<link rel='stylesheet' href="{% static 'css\story3css.css' %}">